# Change these first
owner: vetorial-labs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
runner: "[self-hosted, Linux]"

sites:
  - name: Site da Vetorial
    url: https://www.vetorial.net
  - name: Site da Bitcom
    url: https://www.bitcom.com.br
  - name: Site da Razao
    url: https://www.razaoinfo.com.br
  - name: MK Vetorial
    url: https://erp.vetorial.com/mk/
  - name: MK Bitcom
    url: http://mk.bitcom.com.br/mk/
  - name: MK Razao
    url: http://mk.razaoinfo.net.br/mk/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
